-- Supabase SQL Schema for SkinHealth AI Prediction History Table
-- Copy and run this script in your Supabase SQL Editor (https://app.supabase.com)

CREATE TABLE IF NOT EXISTS public.prediction_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    timestamp TIMESTAMPTZ DEFAULT NOW(),
    image_filename TEXT NOT NULL,
    image_path TEXT NOT NULL,
    predicted_code VARCHAR(50) NOT NULL,
    predicted_name TEXT NOT NULL,
    confidence REAL NOT NULL,
    risk_level VARCHAR(50) NOT NULL,
    is_low_confidence BOOLEAN NOT NULL DEFAULT FALSE,
    ranked_json JSONB NOT NULL,
    guidance TEXT NOT NULL,
    dermatologist_recommendation TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable Row Level Security (RLS)
ALTER TABLE public.prediction_history ENABLE ROW LEVEL SECURITY;

-- Allow public anonymous read access
CREATE POLICY "Allow public read access" 
ON public.prediction_history 
FOR SELECT 
USING (true);

-- Allow public anonymous insert access
CREATE POLICY "Allow public insert access" 
ON public.prediction_history 
FOR INSERT 
WITH CHECK (true);

-- Allow public anonymous delete access
CREATE POLICY "Allow public delete access" 
ON public.prediction_history 
FOR DELETE 
USING (true);
